services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pg-cybersafe-dev
    environment:
      POSTGRES_DB: cyber_safe
      POSTGRES_USER: cyberdev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyberdev -d cyber_safe"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  pgdata:
